apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 1
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: api
        image: mohanprabu2/k8s-mean-ui-angular2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    run: ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    run: ui