apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
spec:
  selector:
    matchLabels:
      app: cron
  replicas: 1
  template:
    metadata:
      labels:
        app: cron
    spec:
      containers:
      - name: cron
        image: mohanprabu2/k8s-mean-cron-python
        env:
        - name: MONGO_DB_IP
          value: 10.244.1.81
