apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
    app: k8s-mean-db
spec:
  selector:
    name: mongo
  type: ClusterIP
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    name: mongo
    app: k8s-mean  
spec:
  selector:
    matchLabels:
      app: mongo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
        app: mongo
    spec:
      schedulerName: stork
      containers:
      - name: mongo
        image: mongo
        imagePullPolicy: "Always"
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongodb
      volumes:
      - name: mongodb
        persistentVolumeClaim:
          claimName: px-mongo-pvc